#==================================================================
# GitHub Pages Configuration
#==================================================================

title: "ECE 4750 Section 1: RTL Design with Verilog"

